export const KEYS = {
  AUTH: {
    SIGNUP: "signup",
    LOGIN: "login",
    CHANGE_PASSWORD: "change-password",
    FORGOT_PASSWORD: "forgot-password",
    VERIFY_OTP: "verify-otp",
    RESEND_OTP: "resend-otp",
    RESET_PASSWORD: "reset-password",
    SIGNUP_GOOGLE: "signup-google",
  },
  UPLOAD: {
    ALL_IMAGE: "upload-image",
    ALL_PDF: "upload-pdf",
    ADD: "upload",
    DELETE: "upload-delete",
  },
  PLAN: {
    BASE: "plan",
    ADD: "add-plan",
    EDIT: "edit-plan",
    DELETE: "delete-plan",
  },
  STORE: {
    BASE: "store",
    ADD: "add-store",
    EDIT: "edit-store",
    DELETE: "delete-store",
  },
  USER: {
    SUBSCRIBE: "subscribe",
  },
  THEME: {
    BASE: "theme",
    ADD: "add-theme",
    EDIT: "edit-theme",
    DELETE: "delete-theme",
  },
  SETTINGS: {
    STORE: "settings-store",
    STORE_UPSERT: "upsert-settings-store",
    DOMAIN: "settings-domain",
    DOMAIN_ADD: "add-settings-domain",
    DOMAIN_EDIT: "edit-settings-domain",
    DOMAIN_DELETE: "delete-settings-domain",
    PAYMENT: "settings-payment",
    PAYMENT_UPSERT: "upsert-settings-payment",
    SHIPPING: "settings-shipping",
    SHIPPING_ADD: "add-settings-shipping",
    SHIPPING_EDIT: "edit-settings-shipping",
    SHIPPING_DELETE: "delete-settings-shipping",
    TAX: "settings-tax",
    TAX_UPSERT: "upsert-settings-tax",
    CHECKOUT: "settings-checkout",
    CHECKOUT_UPSERT: "upsert-settings-checkout",
    MAIL: "settings-mail",
    MAIL_UPSERT: "upsert-settings-mail",
    NOTIFICATION: "settings-notification",
    NOTIFICATION_UPSERT: "upsert-settings-notification",
    REGION: "settings-region",
    REGION_UPSERT: "upsert-settings-region",
    SEO: "settings-seo",
    SEO_UPSERT: "upsert-settings-seo",
    VISUAL: "settings-visual",
    VISUAL_UPSERT: "upsert-settings-visual",
    THEME: "settings-theme",
    THEME_UPSERT: "upsert-settings-theme",
    THEME_PUBLISH: "publish-settings-theme",
  },
  COMPONENT: {
    BASE: "component",
    ADD: "add-component",
    EDIT: "edit-component",
    DELETE: "delete-component",
  },
  CATEGORY: {
    BASE: "category",
    ADD: "add-category",
    EDIT: "edit-category",
    DELETE: "delete-category",
  },
  PAGE: {
    BASE: "page",
    ADD: "add-page",
    EDIT: "edit-page",
    DELETE: "delete-page",
  },
  COLLECTION: {
    BASE: "collection",
    ADD: "add-collection",
    EDIT: "edit-collection",
    DELETE: "delete-collection",
  },
  PRODUCT: {
    BASE: "product",
    ADD: "add-product",
    EDIT: "edit-product",
    DELETE: "delete-product",
  },
  BLOG: {
    BASE: "blog",
    ADD: "add-blog",
    EDIT: "edit-blog",
    DELETE: "delete-blog",
  },
};
