export const PAGE_TITLE = {
  DASHBOARD: "Dashboard",
  AUTH: {
    SIGNIN: "Sign In",
    LOGIN: "Login",
    FORGOT_PASSWORD: "Forgot Password",
    VERIFY_OTP: "Verify OTP",
    RESET_PASSWORD: "Reset Password",
  },
  PLAN: {
    BASE: "Plan",
    ADD: "Add Plan",
    EDIT: "Edit Plan",
  },
  STORES: {
    BASE: "Stores",
    ADD: "Add Stores",
    EDIT: "Edit Stores",
  },
  STORE: {
    DASHBOARD: "Store Dashboard",
    PLANS: "Select Plan",
    SETUP: "Store Setup",
    SETTINGS: {
      BASE: "Settings",
      STORE: "Store Settings",
      DOMAIN: "Domain Settings",
      PAYMENT: "Payment Settings",
      SHIPPING: "Shipping Settings",
      TAX: "Tax Settings",
      CHECKOUT: "Checkout Settings",
      MAIL: "Mail Settings",
      NOTIFICATION: "Notification Settings",
      REGION: "Region Settings",
      SEO: "SEO Settings",
      THEME: "Theme Settings",
      VISUAL: "Visual Settings",
    },
  },
  THEME: {
    BASE: "Theme",
    ADD: "Add Theme",
    EDIT: "Edit Theme",
  },
  COMPONENT: {
    BASE: "Component",
    ADD: "Add Component",
    EDIT: "Edit Component",
  },
  CATEGORY: {
    BASE: "Category",
    ADD: "Add Category",
    EDIT: "Edit Category",
  },
  PAGE: {
    BASE: "Page",
    ADD: "Add Page",
    EDIT: "Edit Page",
  },
  COLLECTION: {
    BASE: "Collection",
    ADD: "Add Collection",
    EDIT: "Edit Collection",
  },
  PRODUCT: {
    BASE: "Product",
    ADD: "Add Product",
    EDIT: "Edit Product",
  },
} as const;
